name: Survival
api-version: "1.15"
depend: [ProtocolLib]
version: "3.1"
description: Gerneral survival plugin
author: phonis
main: src.phonis.survival.Survival
commands:
  chunk:
    description: Handle force loading of chunks
  getcraft:
    description: Shows crafting recipee for item
  find:
    description: Finds a player by name
  bl:
    description: Broadcast your location
  waypoint:
    description: Handle waypoints
  slimemap:
    description: Shows nearby slime chunks
  inspect:
    description: Inspect somebodies inventory
  sleep:
    description: Handle global sleeping
  spec:
    description: Spectator mode interactions
  toggle:
    description: Toggle various server states
  yawsnap:
    description: Snap yaw to closest cardinal direction
  todo:
    description: Handle todo
  setdeathmessage:
    description: Set the deathmessage for a player
  trade:
    description: List and find trades
  findinchest:
    aliases: [fic]
    description: Find material in chest near you
  survivalhelp:
    description: Help with all of the plugin commands
